/**
 * ============================================================================
 * [INTERNAL NOTICE: DEMO DATA LAYER]
 * This file contains strictly labeled simulated demonstration data for
 * TelePlay Ethiopia. No real customer personal data or production records are
 * exposed. It ensures full offline portal functionality and predictable UI preview.
 * ============================================================================
 */

import {
  GameDefinition,
  LeaderboardEntry,
  Tournament,
  DailyRewardItem,
  UserProfile,
} from '../types';

export const DEMO_USER_PROFILE: UserProfile = {
  id: 'usr_demo_ethio_001',
  phoneNumber: '+251 91 142 8890',
  displayName: 'Abebe_Gamer',
  avatarId: 'avatar_eagle',
  isRegistered: true,
  telebirrLinked: true,
  telebirrBalance: 350.0, // 350 ETB in TeleBirr account
  coins: 1420,
  xp: 3850,
  level: 5,
  energy: 5,
  maxEnergy: 5,
  lastEnergyRefillTimestamp: Date.now(),
  subscription: {
    plan: 'weekly',
    isActive: true,
    expiresAt: Date.now() + 5 * 24 * 60 * 60 * 1000, // 5 days remaining
    autoRenew: true,
  },
  streak: {
    current: 4,
    lastClaimedDate: '',
    hasClaimedToday: false,
  },
  highScores: {
    'addis-runner': 14850,
    'habesha-2048': 8192,
    'penalty-shootout': 9,
    'nile-gem-quest': 24100,
    'ethio-trivia': 1250,
    'speed-bumper-derby': 7600,
  },
  achievements: ['first_win', 'streak_3', 'telebirr_link', 'top_100'],
  matchesPlayed: 42,
  trophiesCount: 8,
};

export const INITIAL_GUEST_PROFILE: UserProfile = {
  id: 'usr_guest_' + Math.random().toString(36).substring(2, 8),
  phoneNumber: '',
  displayName: 'Guest Player',
  avatarId: 'avatar_runner',
  isRegistered: false,
  telebirrLinked: false,
  telebirrBalance: 0,
  coins: 100,
  xp: 0,
  level: 1,
  energy: 5,
  maxEnergy: 5,
  lastEnergyRefillTimestamp: Date.now(),
  subscription: {
    plan: 'free',
    isActive: false,
    autoRenew: false,
  },
  streak: {
    current: 1,
    lastClaimedDate: '',
    hasClaimedToday: false,
  },
  highScores: {},
  achievements: [],
  matchesPlayed: 0,
  trophiesCount: 0,
};

/**
 * Modular Games Definition (All Attached Games Integrated)
 */
export const SIX_MODULAR_GAMES: GameDefinition[] = [
  {
    id: 'hill-rider',
    title: 'Hill Climb',
    titleAmharic: 'ሂል ክላይምብ',
    category: 'action',
    genre: 'Action',
    difficulty: 'Medium',
    tagline: 'Conquer steep highland ridges and rugged mountain terrains!',
    description: 'Physics-based 2D hill climbing driving action. Control acceleration and vehicle pitch balance over steep Ethiopian highland hills, rocky gorges, and suspension bridges to reach the summit.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1200&q=80',
    primaryColor: '#0B3B70',
    secondaryColor: '#70C922',
    rating: 4.7,
    playsCount: 119800,
    energyCost: 1,
    featured: true,
    isTrending: true,
    status: 'available',
    featuredWeekly: false,
    instructions: [
      'Hold Gas (Right) to accelerate uphill and release on steep drops to maintain traction',
      'Use Brake / Tilt (Left) to slow down and stabilize buggy balance mid-air',
      'Collect fuel jerrycans along the track before your vehicle engine runs dry',
    ],
    controlsDescription: 'Tap/hold Gas (Right) & Brake (Left) on screen, or use Left/Right arrow keys.',
  },
  {
    id: 'color-rush',
    title: 'Color Rush',
    titleAmharic: 'ከለር ረሽ',
    category: 'arcade',
    genre: 'Arcade',
    difficulty: 'Hard',
    tagline: 'Test your lightning-fast reflex timing against the chromatic rush!',
    description: 'High-speed reflex reaction test. Match incoming chromatic neon pulses and rotating color gates before the countdown runs out. Speed increases with every successful combo!',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    primaryColor: '#70C922',
    secondaryColor: '#0B3B70',
    rating: 4.8,
    playsCount: 132600,
    energyCost: 1,
    featured: true,
    isTrending: true,
    status: 'available',
    featuredWeekly: false,
    instructions: [
      'Watch the target color flash on screen and tap the matching color paddle immediately',
      'Keep your reaction streak alive to trigger the 3x Multiplier Fever mode',
      'Avoid incorrect taps which instantly break your combo streak and cost a life',
    ],
    controlsDescription: 'Tap color buttons or press Arrow keys (Up/Down/Left/Right) in rapid sequence.',
  },
  {
    id: 'pop-balloon',
    title: 'Pop Balloon',
    titleAmharic: 'ፖፕ ባሉን',
    category: 'arcade',
    genre: 'Arcade',
    difficulty: 'Medium',
    tagline: 'Tap and pop the falling colored balloons before they reach the bottom!',
    description: 'Fast-paced reflex game. Tap and pop vibrant falling colored circles while testing your speed, rhythm, and accuracy before any balloons slip past.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    primaryColor: '#EC4899',
    secondaryColor: '#3B82F6',
    rating: 4.9,
    playsCount: 168000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    status: 'available',
    featuredWeekly: false,
    instructions: [
      'Tap or click directly on each falling colored balloon to pop it instantly',
      'Do not tap empty background space or the decorative center ring',
      'Prevent balloons from escaping past the bottom to preserve your 3 hearts',
    ],
    controlsDescription: 'Tap or click falling colored balloons to pop.',
  },
  {
    id: 'candy-blast',
    title: 'Candy Blast',
    titleAmharic: 'ኬንዲ ብላስት',
    category: 'puzzle',
    genre: 'Puzzle',
    difficulty: 'Easy',
    tagline: 'Match vibrant Ethiopian honey candies and sweet jellies!',
    description: 'A delightful confectionery match-3 puzzle. Swap and connect 3 or more delicious honey candies to trigger colorful cascades, sweet sugar blasts, and massive combo multipliers.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80',
    primaryColor: '#e11d48',
    secondaryColor: '#70C922',
    rating: 4.9,
    playsCount: 154200,
    energyCost: 1,
    featured: true,
    isTrending: true,
    status: 'available',
    featuredWeekly: false,
    instructions: [
      'Swap adjacent candies to create horizontal or vertical rows of 3 or more matching colors',
      'Match 4 candies to create explosive Striped Candies that clear entire rows',
      'Combine 5 candies to form a Rainbow Honey Bomb that blasts all candies of the same color',
    ],
    controlsDescription: 'Tap and swipe candies to swap positions.',
  },
  {
    id: 'world-legends',
    title: 'World Legends',
    titleAmharic: 'የዓለም አፈታሪኮች',
    category: 'puzzle',
    genre: 'Puzzle',
    difficulty: 'Medium',
    tagline: 'Journey through epic world history, mythology, and legendary lore!',
    description: 'An immersive knowledge and trivia adventure. Answer intriguing questions on world civilizations, ancient mythology, Ethiopian imperial heritage, and legendary world events.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    primaryColor: '#f59e0b',
    secondaryColor: '#05234A',
    rating: 4.9,
    playsCount: 98700,
    energyCost: 1,
    featured: false,
    isNew: true,
    status: 'available',
    featuredWeekly: false,
    instructions: [
      'Answer 10 rapid multiple-choice legend questions before the 15-second timer runs out',
      'Score bonus speed points by answering accurately within the first 3 seconds',
      'Use 50:50 and Clue lifelines when facing complex historical questions',
    ],
    controlsDescription: 'Tap the correct historical answer card.',
  },
  {
    id: 'archery-strike',
    title: 'Archery Strike',
    titleAmharic: 'የቀስት ውድድር',
    category: 'sports',
    genre: 'Sports',
    difficulty: 'Medium',
    tagline: 'Precision 3D recurve bow target shooting against variable crosswinds!',
    description: 'Skill-based 3D target archery simulation. Aim your sight, account for dynamic wind speed and drop, and release arrows directly into the bullseye.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1544919982-b61976f0ba43?auto=format&fit=crop&w=1200&q=80',
    primaryColor: '#1688C9',
    secondaryColor: '#8BCB3D',
    rating: 4.9,
    playsCount: 142000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    status: 'available',
    featuredWeekly: false,
    instructions: [
      'Hold and drag to align the sight pin with the center target ring',
      'Check the wind indicator dial in the top corner before loosing your arrow',
      'Score 10 points for bullseye shots and maintain your streak for multiplier bonuses',
    ],
    controlsDescription: 'Drag to aim sight, release to shoot arrow.',
  },
  {
    id: 'pop-piano',
    title: 'Pop Piano',
    titleAmharic: 'ፖፕ ፒያኖ',
    category: 'music',
    genre: 'Music',
    difficulty: 'Medium',
    tagline: 'Tap falling glowing keys to chart-topping melodies and rhythms!',
    description: 'Fast rhythm piano tile gameplay featuring popular Ethiopian pop songs, acoustic chords, and global hits. Tap descending piano tiles in sync with the beat to achieve perfect harmony.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1520523839898-5071282543e2?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    primaryColor: '#8b5cf6',
    secondaryColor: '#70C922',
    rating: 4.9,
    playsCount: 187400,
    energyCost: 1,
    featured: true,
    isTrending: true,
    status: 'available',
    featuredWeekly: false,
    instructions: [
      'Tap the descending piano tiles exactly as they hit the rhythm baseline bar',
      'Hold down long note tiles for sustained chord points and acoustic vibrato',
      'Do not tap empty spaces or let any piano note pass the baseline without tapping',
    ],
    controlsDescription: 'Tap keys on screen or use keyboard keys [D] [F] [J] [K].',
  },
];

/**
 * Tournaments Demo Data
 */
export const DEMO_TOURNAMENTS: Tournament[] = [
  {
    id: 'tourney_candy_blast_weekly',
    title: 'Candy Blast Super Cup',
    gameId: 'candy-blast',
    gameTitle: 'Candy Blast',
    cycle: 'weekly',
    bannerImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80',
    prizePoolETB: 10000,
    prizePoolCoins: 50000,
    entryFeeEnergy: 1,
    entryRequirement: '10 Coins Entry',
    startDate: '2026-08-28',
    endDate: '2026-08-31',
    status: 'Live',
    participantsCount: 12450,
    sponsor: 'TeleBirr SuperApp',
    prizes: [
      { rank: '1st Place', reward: '5,000 ETB TeleBirr Transfer', telebirrETB: 5000 },
      { rank: '2nd Place', reward: '2,500 ETB TeleBirr Transfer', telebirrETB: 2500 },
      { rank: '3rd Place', reward: '1,000 ETB TeleBirr Transfer', telebirrETB: 1000 },
      { rank: '4th - 20th', reward: '100 ETB Airtime Voucher', telebirrETB: 100 },
    ],
  },
  {
    id: 'tourney_color_rush_weekly',
    title: 'Color Rush Reflex Challenge',
    gameId: 'color-rush',
    gameTitle: 'Color Rush',
    cycle: 'weekly',
    bannerImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1000&q=80',
    prizePoolETB: 15000,
    prizePoolCoins: 75000,
    entryFeeEnergy: 1,
    entryRequirement: '10 Coins Entry',
    startDate: '2026-08-28',
    endDate: '2026-08-31',
    status: 'Live',
    participantsCount: 9800,
    sponsor: 'EthioTelecom 4G/5G',
    prizes: [
      { rank: '1st Place', reward: '7,500 ETB TeleBirr Transfer', telebirrETB: 7500 },
      { rank: '2nd Place', reward: '3,500 ETB TeleBirr Transfer', telebirrETB: 3500 },
      { rank: '3rd Place', reward: '1,500 ETB TeleBirr Transfer', telebirrETB: 1500 },
      { rank: '4th - 20th', reward: '150 ETB Airtime Recharge', telebirrETB: 150 },
    ],
  },
  {
    id: 'tourney_pop_piano_weekly',
    title: 'Pop Piano Rhythm Cup',
    gameId: 'pop-piano',
    gameTitle: 'Pop Piano',
    cycle: 'weekly',
    bannerImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
    prizePoolETB: 12000,
    prizePoolCoins: 60000,
    entryFeeEnergy: 1,
    entryRequirement: '10 Coins Entry',
    startDate: '2026-08-28',
    endDate: '2026-08-31',
    status: 'Live',
    participantsCount: 11200,
    sponsor: 'EthioTelecom Digital Services',
    prizes: [
      { rank: '1st Place', reward: '6,000 ETB TeleBirr Transfer', telebirrETB: 6000 },
      { rank: '2nd Place', reward: '3,000 ETB TeleBirr Transfer', telebirrETB: 3000 },
      { rank: '3rd Place', reward: '1,000 ETB TeleBirr Transfer', telebirrETB: 1000 },
    ],
  },
  {
    id: 'tourney_world_legends_monthly',
    title: 'World Legends Grand Championship',
    gameId: 'world-legends',
    gameTitle: 'World Legends',
    cycle: 'monthly',
    bannerImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1000&q=80',
    prizePoolETB: 50000,
    prizePoolCoins: 250000,
    entryFeeEnergy: 2,
    entryRequirement: '20 Coins Entry',
    startDate: '2026-08-25',
    endDate: '2026-09-02',
    status: 'Live',
    participantsCount: 24500,
    sponsor: 'EthioTelecom 5G Network',
    prizes: [
      { rank: '1st Place', reward: '25,000 ETB TeleBirr + 6 Months 5G Unlimited', telebirrETB: 25000 },
      { rank: '2nd Place', reward: '12,500 ETB TeleBirr + 3 Months 5G Package', telebirrETB: 12500 },
      { rank: '3rd Place', reward: '6,000 ETB TeleBirr + 1 Month 5G Package', telebirrETB: 6000 },
      { rank: '4th - 10th', reward: '1,000 ETB Airtime Voucher', telebirrETB: 1000 },
      { rank: 'Top 100', reward: '200 ETB Airtime Voucher', telebirrETB: 200 },
    ],
  },
  {
    id: 'tourney_hill_climb_monthly',
    title: 'Highland Hill Climb Championship',
    gameId: 'hill-rider',
    gameTitle: 'Hill Climb',
    cycle: 'monthly',
    bannerImage: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1000&q=80',
    prizePoolETB: 40000,
    prizePoolCoins: 200000,
    entryFeeEnergy: 2,
    entryRequirement: '20 Coins Entry',
    startDate: '2026-08-25',
    endDate: '2026-09-02',
    status: 'Live',
    participantsCount: 19800,
    sponsor: 'TeleBirr SuperApp',
    prizes: [
      { rank: '1st Place', reward: '20,000 ETB TeleBirr Transfer', telebirrETB: 20000 },
      { rank: '2nd Place', reward: '10,000 ETB TeleBirr Transfer', telebirrETB: 10000 },
      { rank: '3rd Place', reward: '5,000 ETB TeleBirr Transfer', telebirrETB: 5000 },
    ],
  },
  {
    id: 'tourney_archery_monthly',
    title: 'Pop Balloon Reflex Championship',
    gameId: 'archery-strike',
    gameTitle: 'Pop Balloon',
    cycle: 'monthly',
    bannerImage: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1000&q=80',
    prizePoolETB: 35000,
    prizePoolCoins: 175000,
    entryFeeEnergy: 2,
    entryRequirement: '20 Coins Entry',
    startDate: '2026-08-25',
    endDate: '2026-09-02',
    status: 'Live',
    participantsCount: 16400,
    sponsor: 'EthioTelecom Digital',
    prizes: [
      { rank: '1st Place', reward: '18,000 ETB TeleBirr Transfer', telebirrETB: 18000 },
      { rank: '2nd Place', reward: '9,000 ETB TeleBirr Transfer', telebirrETB: 9000 },
      { rank: '3rd Place', reward: '4,000 ETB TeleBirr Transfer', telebirrETB: 4000 },
    ],
  },
];

/**
 * Leaderboards Demo Data
 */
export const DEMO_LEADERBOARD_ENTRIES: Record<string, LeaderboardEntry[]> = {
  daily: [
    { id: 'lb_1', rank: 1, userId: 'u_101', displayName: 'Yared_Speed', phoneNumberMasked: '+251 91 **** 812', avatarId: 'avatar_runner', score: 28450, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Addis Ababa', timestamp: '12m ago' },
    { id: 'lb_2', rank: 2, userId: 'u_102', displayName: 'Selam_Pro', phoneNumberMasked: '+251 92 **** 409', avatarId: 'avatar_eagle', score: 26900, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Hawassa', timestamp: '24m ago' },
    { id: 'lb_3', rank: 3, userId: 'u_103', displayName: 'Dawit_99', phoneNumberMasked: '+251 93 **** 611', avatarId: 'avatar_lion', score: 24800, gameId: 'penalty-shootout', gameTitle: 'Highland Shootout', isVip: false, region: 'Adama', timestamp: '45m ago' },
    { id: 'lb_4', rank: 4, userId: 'u_104', displayName: 'Beti_Puzzle', phoneNumberMasked: '+251 91 **** 780', avatarId: 'avatar_crown', score: 21350, gameId: 'habesha-2048', gameTitle: 'Habesha 2048', isVip: true, region: 'Bahir Dar', timestamp: '1h ago' },
    { id: 'lb_5', rank: 5, userId: 'u_105', displayName: 'Tadesse_Apex', phoneNumberMasked: '+251 94 **** 332', avatarId: 'avatar_runner', score: 19800, gameId: 'nile-gem-quest', gameTitle: 'Nile Gem Quest', isVip: false, region: 'Mekelle', timestamp: '2h ago' },
    { id: 'lb_6', rank: 6, userId: 'u_106', displayName: 'Helen_Quiz', phoneNumberMasked: '+251 91 **** 105', avatarId: 'avatar_lion', score: 18400, gameId: 'ethio-trivia', gameTitle: 'Ethio Trivia Master', isVip: false, region: 'Dire Dawa', timestamp: '2h ago' },
    { id: 'lb_7', rank: 7, userId: 'u_107', displayName: 'Kidus_Goal', phoneNumberMasked: '+251 92 **** 991', avatarId: 'avatar_eagle', score: 16750, gameId: 'penalty-shootout', gameTitle: 'Highland Shootout', isVip: true, region: 'Addis Ababa', timestamp: '3h ago' },
    { id: 'lb_8', rank: 8, userId: 'u_108', displayName: 'Marta_Derby', phoneNumberMasked: '+251 96 **** 554', avatarId: 'avatar_crown', score: 15200, gameId: 'speed-bumper-derby', gameTitle: 'Speed Bumper Derby', isVip: false, region: 'Jimma', timestamp: '3h ago' },
  ],
  weekly: [
    { id: 'lb_w1', rank: 1, userId: 'u_201', displayName: 'Kassahun_Apex', phoneNumberMasked: '+251 91 **** 300', avatarId: 'avatar_crown', score: 142800, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Addis Ababa', timestamp: '2d ago' },
    { id: 'lb_w2', rank: 2, userId: 'u_202', displayName: 'Almaz_Legend', phoneNumberMasked: '+251 91 **** 981', avatarId: 'avatar_lion', score: 128400, gameId: 'habesha-2048', gameTitle: 'Habesha 2048', isVip: true, region: 'Adama', timestamp: '1d ago' },
    { id: 'lb_w3', rank: 3, userId: 'u_203', displayName: 'Solomon_Strike', phoneNumberMasked: '+251 93 **** 447', avatarId: 'avatar_eagle', score: 119500, gameId: 'penalty-shootout', gameTitle: 'Highland Shootout', isVip: true, region: 'Hawassa', timestamp: '3d ago' },
    { id: 'lb_w4', rank: 4, userId: 'u_204', displayName: 'Genet_Gems', phoneNumberMasked: '+251 92 **** 112', avatarId: 'avatar_runner', score: 98700, gameId: 'nile-gem-quest', gameTitle: 'Nile Gem Quest', isVip: false, region: 'Dire Dawa', timestamp: '4d ago' },
    { id: 'lb_w5', rank: 5, userId: 'u_205', displayName: 'Biruk_Trivia', phoneNumberMasked: '+251 94 **** 882', avatarId: 'avatar_crown', score: 87600, gameId: 'ethio-trivia', gameTitle: 'Ethio Trivia Master', isVip: false, region: 'Gondar', timestamp: '2d ago' },
  ],
  alltime: [
    { id: 'lb_a1', rank: 1, userId: 'u_301', displayName: 'Moges_GrandMaster', phoneNumberMasked: '+251 91 **** 001', avatarId: 'avatar_crown', score: 940500, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Addis Ababa', timestamp: 'Aug 2026' },
    { id: 'lb_a2', rank: 2, userId: 'u_302', displayName: 'Aster_Champion', phoneNumberMasked: '+251 91 **** 552', avatarId: 'avatar_lion', score: 815200, gameId: 'penalty-shootout', gameTitle: 'Highland Shootout', isVip: true, region: 'Bishoftu', timestamp: 'Aug 2026' },
    { id: 'lb_a3', rank: 3, userId: 'u_303', displayName: 'Yohannes_Pro', phoneNumberMasked: '+251 92 **** 783', avatarId: 'avatar_eagle', score: 760400, gameId: 'habesha-2048', gameTitle: 'Habesha 2048', isVip: true, region: 'Bahir Dar', timestamp: 'Jul 2026' },
  ],
  tournament: [
    { id: 'lb_t1', rank: 1, userId: 'u_401', displayName: 'Addis_Sonic', phoneNumberMasked: '+251 91 **** 449', avatarId: 'avatar_crown', score: 48900, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Addis Ababa', timestamp: '30m ago' },
    { id: 'lb_t2', rank: 2, userId: 'u_402', displayName: 'Tigist_Fast', phoneNumberMasked: '+251 93 **** 201', avatarId: 'avatar_lion', score: 46200, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Hawassa', timestamp: '1h ago' },
    { id: 'lb_t3', rank: 3, userId: 'u_403', displayName: 'Elias_Volt', phoneNumberMasked: '+251 92 **** 873', avatarId: 'avatar_runner', score: 44100, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: false, region: 'Adama', timestamp: '2h ago' },
    { id: 'lb_t4', rank: 4, userId: 'u_404', displayName: 'Mesfin_Rush', phoneNumberMasked: '+251 91 **** 662', avatarId: 'avatar_eagle', score: 41800, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Mekelle', timestamp: '3h ago' },
  ],
};

/**
 * 7-Day Daily Streak Reward Ladder
 */
export const DAILY_REWARD_LADDER: DailyRewardItem[] = [
  { day: 1, coins: 50, energy: 1, badge: 'Novice Day' },
  { day: 2, coins: 100, energy: 1, badge: 'Double Boost' },
  { day: 3, coins: 150, energy: 2, badge: 'Streak Power' },
  { day: 4, coins: 250, energy: 2, badge: 'Bronze Rank' },
  { day: 5, coins: 400, energy: 3, badge: 'Silver Tier' },
  { day: 6, coins: 600, energy: 3, badge: 'Gold Rush' },
  { day: 7, coins: 1200, energy: 5, badge: 'Walia Grand Chest', special: true },
];

/**
 * Rewarded Ads Catalog (EthioTelecom & TeleBirr sponsored ads)
 */
export const DEMO_TELECOM_ADS = [
  {
    id: 'ad_telebirr_superapp',
    brand: 'TeleBirr SuperApp',
    title: 'Pay bills, send money & earn cashbacks instantly!',
    tagline: 'Ethiopia’s #1 Digital Payment Lifestyle Platform',
    videoBanner: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 5,
    ctaText: 'Open TeleBirr SuperApp',
    accentColor: '#70C922',
  },
  {
    id: 'ad_ethio_5g_router',
    brand: 'EthioTelecom 5G Ultra Broadband',
    title: 'Experience blistering Gigabit speeds across 120+ cities!',
    tagline: 'Connect your home & gaming stations with 0-ping latency',
    videoBanner: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 5,
    ctaText: 'Upgrade to 5G Now',
    accentColor: '#0B3B70',
  },
  {
    id: 'ad_ethio_youth_package',
    brand: 'EthioTelecom Youth Chill Pack',
    title: 'Unlimited Social Media + 10GB Gaming Data at just 50 ETB',
    tagline: 'Empowering the next generation of digital creators',
    videoBanner: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 5,
    ctaText: 'Dial *999# to Subscribe',
    accentColor: '#70C922',
  },
];
